name: test
on: 
  - pull_request
defaults:
  run:
    shell: bash
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        dbimage:
          - mysql:5.7
          - mysql:8.0
          - mariadb:10.3
          - mariadb:10.7
          - percona:8.0
        runner:
          - swift:5.5-focal
          - swift:5.6-focal
          - swiftlang/swift:nightly-main-focal
    container: ${{ matrix.runner }}
    runs-on: ubuntu-latest
    services:
      mysql-a:
        image: ${{ matrix.dbimage }}
        env: 
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
          MYSQL_DATABASE: vapor_database
      mysql-b:
        image: ${{ matrix.dbimage }}
        env: 
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
          MYSQL_DATABASE: vapor_database
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests with Thread Sanitizer
        run: swift test --sanitize=thread
        env:
          LOG_LEVEL: info
          MYSQL_HOSTNAME_A: mysql-a
          MYSQL_HOSTNAME_B: mysql-b
  macos:
    strategy:
      fail-fast: false
      matrix:
        formula: 
          - mysql
          - mysql@5.7
          - mariadb
          - percona-server
        xcode:
          - latest
          - latest-stable
        macos:
          - macos-11
          - macos-12
        include:
          - username: root
          - formula: mariadb
            username: runner
    runs-on: ${{ matrix.macos }}
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: ${{ matrix.xcode }}
      - name: Install MySQL server from Homebrew
        run: brew install ${{ matrix.formula }} && brew link --force ${{ matrix.formula }}
      - name: Start MySQL server
        run: brew services start ${{ matrix.formula }}
      - name: Wait for MySQL server to be ready
        run: until echo | mysql -u${{ matrix.username }}; do sleep 1; done
        timeout-minutes: 5
      - name: Set up MySQL databases and privileges
        run: |
          mysql -u${{ matrix.username }} --batch <<-'SQL'
              CREATE USER vapor_username@localhost IDENTIFIED BY 'vapor_password';
              CREATE DATABASE vapor_database_a; GRANT ALL PRIVILEGES ON vapor_database_a.* TO vapor_username@localhost;
              CREATE DATABASE vapor_database_b; GRANT ALL PRIVILEGES ON vapor_database_b.* TO vapor_username@localhost;
          SQL
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests with Thread Sanitizer
        run: swift test
        env: 
          LOG_LEVEL: info
          MYSQL_HOSTNAME_A: '127.0.0.1'
          MYSQL_HOSTNAME_B: '127.0.0.1'
          MYSQL_DATABASE_A: vapor_database_a
          MYSQL_DATABASE_B: vapor_database_b
